title: Web Design Basics Fall 2018
email: patshiu@newschool.edu
description: >- # this means to ignore newlines until "baseurl:"
  Web Design Basics is designed to introduce students to programming as a creative medium—as a way of making and exploring. The coursework focuses on developing a vocabulary of interaction design principles which can then be applied across a range of platforms. Students are encouraged to experiment with various media, tools, and techniques, ultimately producing a portfolio of interactive and visual projects designed for the screen. An emphasis is placed on typography as it applies to a screen context, research-based problem solving and a “learning through making” approach to technical skill building. Historical and current interaction design precedents will be discussed.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thesyllabus.website" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - _pages
  - _guides

sass:
  style: compressed
